hl.config({ autogenerated = false })

------------------
---- IMPORTS -----
------------------

require("lua.monitors")
require("lua.autostart")
require("lua.devices")
require("lua.base")
require("lua.keybinds")
require("lua.windows")
